development:
  adapter: postgresql
  encoding: unicode
  database: writemap_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: writemap_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: writemap_production
  pool: 5
  username: postgres
  password: postgres
